version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/golang/Dockerfile
    volumes:
      - ./chitchat:/go/src/chitchat
    ports:
      - 8080:8080
    environment: 
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
    tty: true
    depends_on: 
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

